steps:
  # Pull frontend
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      git submodule init
      git submodule update
      
  # Install dependencies for the frontend
  - name: 'node:21'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend_src'

  # Build the frontend
  - name: 'node:21'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend_src'

  # Install Python dependencies
  - name: 'python:3.10'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']


timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
